# Custom section is used to store configurations that might be repetative.
# Please read YAML documentation for details on how to use substitutions and anchors.
custom:
  basic-cluster-props: &basic-cluster-props
    spark_version: "12.2.x-scala2.12"
    init_scripts:
    - dbfs:
        destination: dbfs:/FileStore/geospatial/mosaic/gdal/mosaic-gdal-init.sh

  basic-static-cluster: &basic-static-cluster
    new_cluster:
      <<: *basic-cluster-props
      autoscale:
        min_workers: 2
        max_workers: 8
      node_type_id: "i3.xlarge"


environments:
  default:
    workflows:
      - name: "gdal_rasterio_demo_dbx"
        job_clusters:
          - job_cluster_key: "dbx_gdal_cluster"
            <<: *basic-static-cluster
        tasks:
          - task_key: "create_reference_file"
            job_cluster_key: "dbx_gdal_cluster"
            notebook_task:
              notebook_path: create_reference_file
              base_parameters:
                catalog_name: tim_dikland
                schema_name: image_puneet
                mode: DBFS
              source: GIT
          - task_key: "bronze_transformation"
            depends_on:
            - task_key: create_reference_file
            job_cluster_key: "dbx_gdal_cluster"
            notebook_task:
              notebook_path: bronze_transformation
              base_parameters:
                catalog_name: tim_dikland
                schema_name: image_puneet
                mode: DBFS
                bronze_image_location: bronze
              source: GIT 
          - task_key: "silver_transformation"
            depends_on:
            - task_key: "bronze_transformation"
            job_cluster_key: "dbx_gdal_cluster"
            notebook_task:
              notebook_path: "silver_transformation"
              base_parameters:
                catalog_name: tim_dikland
                schema_name: image_puneet
                mode: DBFS
                silver_image_location: silver
              source: GIT         
          - task_key: "gold_transformation"
            depends_on:
            - task_key: "silver_transformation"
            job_cluster_key: "dbx_gdal_cluster"
            notebook_task:
              notebook_path: "gold_transformation"
              base_parameters:
                catalog_name: tim_dikland
                schema_name: image_puneet
                mode: DBFS
                gold_image_location: silver
              source: GIT       
        git_source:
          git_url: https://github.com/puneet-jain159/gdal_rasterio_demo
          git_provider: gitHub
          git_branch: main

