name: CI pipeline

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: setup.py

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies and project in dev mode
        run: |
          pip install -e ".[local,test]"

      - name: Clone the repository if not exist
        continue-on-error: true
        run: |
            databricks repos create --url https://github.com/puneet-jain159/gdal_rasterio_demo.git --provider gitHub --path /Repos/puneet.jain@databricks.com/gdal-rasterio-demo

      - name: Clone the repository if not exist
        run: |
            databricks repos update --path /Repos/puneet.jain@databricks.com/gdal-rasterio-demo --branch main
    
      - name: Create the workflow
        run: |
          echo "Creating the workflow"
          dbx deploy --workflows=gdal_rasterio_demo_dbx --no-package


